dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),  # django自带管理系统
    url(r'^user/', include("user.urls", namespace="user")),  # 用户系统
    url(r'^', include("goods.urls", namespace="goods")),  # 商品系统
    url(r'^tinymce/', include('tinymce.urls')), #tinymsc 富文本

    url(r'^provinces/', include("provinces.urls", namespace="provinces")),  # 省市区三级联动
]

dailyfresh/user/urls.py
from django.conf.urls import include, url
from user import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # 注册、登录
    url(r'^register$', views.RegisterView.as_view(), name="register"),  # 注册
    url(r'^active/(?P<token>.*)$', views.ActiveView.as_view(), name="active"),  # 帐号激活
    url(r'^login$', views.LoginView.as_view(), name="login"),  # 登录

    #忘记密码
    url(r'^forget_password$', views.ForgetPasswordView.as_view(), name="forget_password"),  # 忘记密码
    url(r'^update_password/(?P<token>.*)$', views.UpdatePasswordView.as_view(), name="update_password"),  # 修改密码

    # 验证码
    url(r'^validate_code$', views.validate_cod, name="validate_code"),  # 注册验证码
    #首页
    url(r'^index$', views.index, name="index"),  # 天天生鲜首页
    #退出
    url(r'^logout$', views.logout_view, name="logout"),  # 天天生鲜首页

    # 用户中心三个页面跳转
    # url(r'^$', login_required(views.UserInfoView.as_view()), name="user"),#用户个人信息页
    # url(r'^order$', login_required(views.UserOrderView.as_view()), name="order"),#用户个人订单页
    # url(r'^address$', login_required(views.UserAddressView.as_view()), name="address"),#用户收货地址页

    url(r'^$', views.UserInfoView.as_view(), name="user"),  # 用户个人信息页
    url(r'^order$', views.UserOrderView.as_view(), name="order"),  # 用户个人订单页
    url(r'^address$', views.UserAddressView.as_view(), name="address"),  # 用户收货地址页
    # 地址编辑
    url(r'^address_show$', views.address_show, name="address_show"),  # 用户全部收货地址页
    url(r'^address_all$', views.UserAddressAllView.as_view(), name="address_all"),  # 用户全部收货地址页
    url(r'^remove_addr/(?P<Rmpk>.*)$', views.remove_addr, name="remove_addr"),  # 用户全部收货地址页
    url(r'^address/(?P<Uppk>.*)$', views.UpdateAddress.as_view(), name="update_addr"),  # 用户收货地址页
    url(r'^update_is_default/(?P<Updefault>.*)$', views.UpdateDefault.as_view(), name="update_is_default"),  # 用户收货地址页


    url(r'^car$', views.UserCarView.as_view(), name="car"),  # 用户收货地址页

]

dailyfresh/templates/base1-bottom.html
{#所有都有的页面#}

{#以下继承：#}

{#base2-bottom-and-head-top.html#}
{#base3-bottom-head_top-head_head-user_car.html#}
{#base3-bottom-head_top-head_head-user_seek.html#}

{#6、login.html 登录页面#}
{#7、register.html 注册页面，已加入了初步的表单验证效果，此效果在课程中已讲述如何制作。#}

{% load static from staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {% block head-title %}
        <title>base-one-bottom.html</title>
    {% endblock %}
    {% block head-content %}

    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
{% block body-one %}
{% endblock %}


<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>
{% block body-buttem %}
{% endblock %}
</body>
</html>
{% block buttem_buttem %}
{% endblock %}

dailyfresh/templates/base2-bottom-and-head-top.html
{#除了 注册和登录 都有的页面#}
{##}
{#以下继承#}
{#base3-bottom-head_top-head_head-user_car.html#}
{#base3-bottom-head_top-head_head-user_seek.html#}
{##}
{#4、cart.html 我的购物车页，列出已放入购物车上的商品#}
{#5、place_order.html 提交订单页#}


{% extends 'base1-bottom.html' %}
{% load static from staticfiles %}
{% block head-title %}
    <title>base-two-bottom-and-head-top.html</title>
{% endblock %}
{% block body-one %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天生鲜!</div>
            <div class="fr">
                <div class="login_info fl">
                    欢迎您：<em>张 山</em>
                </div>
                <div class="login_btn fl">
                    <a href="{% url 'user:index' %}">天天生鲜首页</a>
                    <span>|</span>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'user:user' %}">欢迎您：{{ request.user }}</a>
                    {% else %}
                        <a href="{% url 'user:login' %}">登录</a>
                    {% endif %}
                    <span>|</span>
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'user:logout' %}">退出</a>
                    {% else %}
                        <a href="{% url 'user:register' %}">注册</a>
                    {% endif %}
{#                    <a href="{% url 'user:register' %}">注册</a>#}
                </div>
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:user' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'user:car' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'user:order' %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
    {% block body-two %}
    {% endblock %}
{% endblock %}



{% comment %}
{% load static from staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {% block head-title %}
        <title>天天生鲜-首页</title>
    {% endblock %}
    {% block head-content %}

    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
{% block body-one %}
{% endblock %}

{% block body-buttem %}
{% endblock %}
<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>
</body>
</html>{% endcomment %}

dailyfresh/templates/base3-bottom-head_top-head_head-user_car.html
{#1、index.html   网站首页#}
{#2、list.html  商品列表页#}
{#3、detail.html  商品详情页#}
{% extends 'base2-bottom-and-head-top.html' %}
{% load static from staticfiles %}
{% block head-title %}
    <title>base3-bottom-head_top-head_head-user_car.html</title>
{% endblock %}
{% block body-two %}
    <div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src=" {% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="cart.html" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">0</div>
		</div>
	</div>
    {% block body3 %}
    {% endblock %}
{% endblock %}



dailyfresh/templates/base3-bottom-head_top-head_head-user_seek.html
{#8、user_center_info.html 用户中心-用户信息页 用户中心功能一，查看用户的基本信#}
{#9、user_center_order.html 用户中心-用户订单页 用户中心功能二，查看用户的全部订单#}
{#10、user_center_site.html 用户中心-用户收货地址页 用户中心功能三，查看和设置用户的收货地址#}

{% extends 'base2-bottom-and-head-top.html' %}
{% load static from staticfiles %}
{% block head-title %}
    <title>base3-bottom-head_top-head_head-user_car.html</title>
{% endblock %}
{% block body-two %}
    <div class="search_bar clearfix">
        <a href="index.html" class="logo fl"><img src=" {% static 'images/logo.png' %}"></a>
        <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
        <div class="search_con fr">
            <input type="text" class="input_text fl" name="" placeholder="搜索商品">
            <input type="button" class="input_btn fr" name="" value="搜索">
        </div>
    </div>
    <div class="main_con clearfix">

        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'user:user' %}" {% if page == '1' %} class="active"{% endif %}>· 个人信息</a></li>
                <li><a href="{% url 'user:order' %}" {% if page == '2' %} class="active"{% endif %}>· 全部订单</a></li>
                <li><a href="{% url 'user:address' %}" {% if page == '3' %} class="active"{% endif %}>· 收货地址</a></li>
            </ul>
        </div>
        {% block body3-has-seek %}
        {% endblock %}
    </div>
{% endblock %}



dailyfresh/templates/cart.html
{% extends 'base2-bottom-and-head-top.html' %}
{% load static from staticfiles %}
{% block head-title %}
    	<title>天天生鲜-购物车</title>
{% endblock %}

{% block body-two %}
    <div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src=" {% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>

	<div class="total_count">全部商品<em>2</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src=" {% static 'images/goods/goods012.jpg' %}"></li>
		<li class="col03">奇异果<br><em>25.80元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">25.80元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="1">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07">25.80元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>

	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="" checked></li>
		<li class="col02"><img src=" {% static 'images/goods/goods003.jpg' %}"></li>
		<li class="col03">大兴大棚草莓<br><em>16.80元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">16.80元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="1">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07">16.80元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>


	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>
		<li class="col04"><a href="place_order.html">去结算</a></li>
	</ul>
{% endblock %}




















{#{% load static from staticfiles %}#}
{#<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">#}
{#<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">#}
{#<head>#}
{#	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">#}
{#	<title>天天生鲜-购物车</title>#}
{#	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">#}
{#	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">#}
{#</head>#}
{#<body>#}
{#	<div class="header_con">#}
{#		<div class="header">#}
{#			<div class="welcome fl">欢迎来到天天生鲜!</div>#}
{#			<div class="fr">#}
{#				<div class="login_info fl">#}
{#					欢迎您：<em>张 山</em>#}
{#				</div>#}
{#				<div class="login_btn fl">#}
{#					<a href="login.html">登录</a>#}
{#					<span>|</span>#}
{#					<a href="register.html">注册</a>#}
{#				</div>#}
{#				<div class="user_link fl">#}
{#					<span>|</span>#}
{#					<a href="user_center_info.html">用户中心</a>#}
{#					<span>|</span>#}
{#					<a href="cart.html">我的购物车</a>#}
{#					<span>|</span>#}
{#					<a href="user_center_order.html">我的订单</a>#}
{#				</div>#}
{#			</div>#}
{#		</div>		#}
{#	</div>#}
{##}
{#	<div class="search_bar clearfix">#}
{#		<a href="index.html" class="logo fl"><img src=" {% static 'images/logo.png' %}"></a>#}
{#		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;购物车</div>#}
{#		<div class="search_con fr">#}
{#			<input type="text" class="input_text fl" name="" placeholder="搜索商品">#}
{#			<input type="button" class="input_btn fr" name="" value="搜索">#}
{#		</div>		#}
{#	</div>#}
{##}
{#	<div class="total_count">全部商品<em>2</em>件</div>	#}
{#	<ul class="cart_list_th clearfix">#}
{#		<li class="col01">商品名称</li>#}
{#		<li class="col02">商品单位</li>#}
{#		<li class="col03">商品价格</li>#}
{#		<li class="col04">数量</li>#}
{#		<li class="col05">小计</li>#}
{#		<li class="col06">操作</li>#}
{#	</ul>#}
{#	<ul class="cart_list_td clearfix">#}
{#		<li class="col01"><input type="checkbox" name="" checked></li>#}
{#		<li class="col02"><img src=" {% static 'images/goods/goods012.jpg' %}"></li>#}
{#		<li class="col03">奇异果<br><em>25.80元/500g</em></li>#}
{#		<li class="col04">500g</li>#}
{#		<li class="col05">25.80元</li>#}
{#		<li class="col06">#}
{#			<div class="num_add">#}
{#				<a href="javascript:;" class="add fl">+</a>#}
{#				<input type="text" class="num_show fl" value="1">	#}
{#				<a href="javascript:;" class="minus fl">-</a>	#}
{#			</div>#}
{#		</li>#}
{#		<li class="col07">25.80元</li>#}
{#		<li class="col08"><a href="javascript:;">删除</a></li>#}
{#	</ul>#}
{##}
{#	<ul class="cart_list_td clearfix">#}
{#		<li class="col01"><input type="checkbox" name="" checked></li>#}
{#		<li class="col02"><img src=" {% static 'images/goods/goods003.jpg' %}"></li>#}
{#		<li class="col03">大兴大棚草莓<br><em>16.80元/500g</em></li>#}
{#		<li class="col04">500g</li>#}
{#		<li class="col05">16.80元</li>#}
{#		<li class="col06">#}
{#			<div class="num_add">#}
{#				<a href="javascript:;" class="add fl">+</a>#}
{#				<input type="text" class="num_show fl" value="1">	#}
{#				<a href="javascript:;" class="minus fl">-</a>	#}
{#			</div>#}
{#		</li>#}
{#		<li class="col07">16.80元</li>#}
{#		<li class="col08"><a href="javascript:;">删除</a></li>#}
{#	</ul>#}
{#	#}
{##}
{#	<ul class="settlements">#}
{#		<li class="col01"><input type="checkbox" name="" checked=""></li>#}
{#		<li class="col02">全选</li>#}
{#		<li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>#}
{#		<li class="col04"><a href="place_order.html">去结算</a></li>#}
{#	</ul>#}
{##}
{#	<div class="footer">#}
{#		<div class="foot_link">#}
{#			<a href="#">关于我们</a>#}
{#			<span>|</span>#}
{#			<a href="#">联系我们</a>#}
{#			<span>|</span>#}
{#			<a href="#">招聘人才</a>#}
{#			<span>|</span>#}
{#			<a href="#">友情链接</a>		#}
{#		</div>#}
{#		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>#}
{#		<p>电话：010-****888    京ICP备*******8号</p>#}
{#	</div>#}
{#	#}
{#</body>#}
{#</html>#}

dailyfresh/templates/forget_password.html
{% extends 'base1-bottom.html' %}
{% load static from staticfiles %}
{% block head-title %}
    <title>天天生鲜-登录</title>
{% endblock %}

{% block body-one %}
    <div class="login_top clearfix">
        <a href="index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">日夜兼程 · 急速送达</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>找回密码</h1>
                    <a href="{% url 'user:login' %}">立即登录</a>
                </div>
                <div class="form_input">
                    <form method="post">
                        {#                <form action="{% url 'user:login' %}" method="post">#}
                        {% csrf_token %}
                        <input type="text" name="username" class="name_input" placeholder="请输入用户名">
                        <input type="text" name="email" class="pass_input" placeholder="请输入绑定邮箱">
                        <div class="more_input clearfix">
                            {#                            <input type="checkbox" name="remember" value="1" checked="checked">#}
                            {#                            <label>记住用户名</label>#}
                            {#                            <a href="{% url 'user:forget_password' %}">忘记密码</a>#}
                            <div style="clear: both">
                                <b style="color: #c40000;align-content: center">{{ errors }}</b>
                            </div>
                        </div>

                        <input type="submit" name="" value="提交" class="input_submit">
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}







{% comment %}
{% load static from staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>天天生鲜-登录</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
<div class="login_top clearfix">
    <a href="index.html" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
</div>

<div class="login_form_bg">
    <div class="login_form_wrap clearfix">
        <div class="login_banner fl"></div>
        <div class="slogan fl">日夜兼程 · 急速送达</div>
        <div class="login_form fr">
            <div class="login_title clearfix">
                <h1>用户登录</h1>
                <a href="{% url 'user:register' %}">立即注册</a>
            </div>
            <div class="form_input">
                <form action="{% url 'user:login' %}" method="post">
                    {% csrf_token %}
                    <input type="text" name="username" class="name_input" placeholder="请输入用户名"
                           value={{ remember_username }}>
                    <div class="user_error">输入错误</div>
                    <input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
                    <div class="pwd_error">输入错误</div>
                    <div class="more_input clearfix">
                        <input type="checkbox" name="remember" value="1" checked="checked">
                        <label>记住用户名</label>
                        <a href="#">忘记密码</a>
                        <div style="clear: both">
                            <b style="color: #c40000;align-content: center">{{ errors }}</b>
                        </div>
                    </div>

                    <input type="submit" name="" value="登录" class="input_submit">
                </form>
            </div>
        </div>
    </div>
</div>

<div class="footer no-mp">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>

</body>
</html>{% endcomment %}

dailyfresh/templates/register.html
{% extends 'base1-bottom.html' %}
{% load static from staticfiles %}
{% block head-title %}
    <title>天天生鲜-注册</title>
{% endblock %}
{% block head-content %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
    <style>
        #validate_code_img{
            cursor: pointer;
        }
    </style>
{% endblock %}
{% block body-one %}
    <div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url 'user:register' %}" method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">{{ errmsg }}</span>
                        <span>{{ name_error }}</span>

					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
                        <span>{{ pwd_error }}</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
                        <span>{{ cpwd_error }}</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
                        <span>{{ email_error }}</span>
					</li>
                    <li>
                        <label>验证码</label>
                        <img src="{% url 'user:validate_code' %}" id="validate_code_img">
                    </li>
                    <li>
                        <label>输入验证码</label>
                        <input type="text" name="validate_code" id="validate_code">
                        <span>{{ validate_code_error }}</span>
                    </li>
                    <b>{{ errmsg }}{{ allow_error }}</b>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>
{% endblock %}
{% block buttem_buttem %}
<script>
    var validate_code_img=document.getElementById("validate_code_img")
    var url = '/user/validate_code?num='
    validate_code_img.onclick = function () {
        var num=new Date().dateTime
        url += num
        validate_code_img.src = url


    }
</script>
{% endblock %}



{% comment %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

</head>
<body>
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url 'user:register' %}" method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">{{ errmsg }}</span>
                        <span>{{ name_error }}</span>

					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
                        <span>{{ pwd_error }}</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
                        <span>{{ cpwd_error }}</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
                        <span>{{ email_error }}</span>
					</li>
                    <li>{{ errmsg }}{{ allow_error }}</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>{% endcomment %}

dailyfresh/templates/test-file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                <td>上传文件</td>
                <td><input type="file" name="file1"></td>
            </tr>
            <tr>
                <td colspan="2"><input type="submit"></td>
            </tr>
        </table>
    </form>
</div>
</body>
</html>